//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventCodeSolution {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventCodeSolution.InputResources", typeof(InputResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position=&lt; 21373,  53216&gt; velocity=&lt;-2, -5&gt;
        ///position=&lt;-10460, -31621&gt; velocity=&lt; 1,  3&gt;
        ///position=&lt; 21353, -42222&gt; velocity=&lt;-2,  4&gt;
        ///position=&lt; 53136, -52828&gt; velocity=&lt;-5,  5&gt;
        ///position=&lt; 42542, -21012&gt; velocity=&lt;-4,  2&gt;
        ///position=&lt;-42304, -10407&gt; velocity=&lt; 4,  1&gt;
        ///position=&lt; 21337,  21407&gt; velocity=&lt;-2, -2&gt;
        ///position=&lt;-42297,  42612&gt; velocity=&lt; 4, -4&gt;
        ///position=&lt; 31921, -42227&gt; velocity=&lt;-3,  4&gt;
        ///position=&lt;-21087,  10800&gt; velocity=&lt; 2, -1&gt;
        ///position=&lt;-52877, -31621&gt; velocity=&lt; 5,  3&gt;
        ///position=&lt; 42532, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1308.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initial state: ..#..###...#####.#.#...####.#..####..###.##.#.#.##.#....#....#.####...#....###.###..##.#....#######
        ///
        ///..### =&gt; .
        ///.##.# =&gt; #
        ///#..#. =&gt; .
        ///#.#.# =&gt; #
        ///###.. =&gt; #
        ///.#..# =&gt; .
        ///##..# =&gt; #
        ///.###. =&gt; #
        ///..#.. =&gt; .
        ///..... =&gt; .
        ///##### =&gt; .
        ///.#... =&gt; #
        ///...#. =&gt; #
        ///#...# =&gt; #
        ///####. =&gt; .
        ///.#### =&gt; .
        ///##.## =&gt; #
        ///...## =&gt; .
        ///..##. =&gt; .
        ///#.##. =&gt; .
        ///#.... =&gt; .
        ///.#.#. =&gt; .
        ///..#.# =&gt; #
        ///#.#.. =&gt; #
        ///##... =&gt; #
        ///##.#. =&gt; .
        ///#..## =&gt; .
        ///.##.. =&gt; .
        ///#.### =&gt; .
        ///....# =&gt; .
        ///.#.## =&gt; #
        ///###.# =&gt; #.
        /// </summary>
        internal static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +16
        ///-2
        ///-5
        ///+1
        ///-12
        ///-1
        ///-8
        ///+12
        ///+5
        ///-18
        ///-12
        ///-11
        ///-1
        ///+2
        ///-8
        ///-6
        ///-1
        ///-17
        ///-18
        ///+16
        ///-4
        ///+18
        ///+7
        ///-4
        ///+13
        ///+11
        ///-5
        ///+11
        ///-8
        ///+15
        ///+8
        ///-16
        ///+15
        ///+10
        ///-19
        ///-17
        ///+5
        ///-13
        ///+10
        ///+14
        ///+16
        ///+8
        ///+14
        ///-8
        ///+19
        ///-17
        ///+14
        ///+12
        ///+8
        ///+9
        ///-11
        ///+1
        ///+2
        ///-16
        ///+19
        ///+13
        ///-5
        ///+6
        ///-10
        ///-6
        ///+4
        ///-15
        ///+20
        ///+18
        ///-14
        ///+15
        ///+3
        ///+4
        ///-3
        ///-9
        ///+1
        ///+18
        ///+8
        ///+2
        ///-11
        ///+19
        ///-3
        ///-10
        ///+14
        ///+12
        ///+6
        ///-17
        ///-14
        ///-10
        ///-18
        ///+19
        ///+4
        ///+12
        ///-18
        ///-4
        ///-8
        ///-4
        ///-20
        ///-16
        ///-1
        ///-18
        ///+2
        ///-17
        ///-17
        ///+7
        ///-12
        ///-3
        ///+4
        ///+9
        ///+6
        ///+9
        ///+6
        ///+1
        ///-17
        ///+13
        ///+14
        ///-2
        ///+8
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cvfueihajytpmrdkgsxfqplbxn
        ///cbzueihajytnmrdkgtxfqplbwn
        ///cvzucihajytomrdkgstfqplqwn
        ///cvzueilajytomrdkgsxfqwnbwn
        ///cvzueihajytomrdkgsgwqphbwn
        ///wuzuerhajytomrdkgsxfqplbwn
        ///cyzueifajybomrdkgsxfqplbwn
        ///cvzueihajxtomrdkgpxfqplmwn
        ///ivzfevhajytomrdkgsxfqplbwn
        ///cvzueihajytomrdlgsxfqphbbn
        ///uvzueihajjtomrdkgsxfqpobwn
        ///cvzupihajytomrdkgsxfqplpwe
        ///cvzueihajyvomrdkgsxfqplbrl
        ///cczueihajytomrdkgsnfqpxbwn
        ///cvzueigajytdmrdkgsxyqplbwn
        ///cvzujihljytomrdkgsxuqplbwn
        ///cvzueisajytomrddgsxkqplbwn
        ///cvzneihajytomrdkgsgaqplbwn
        ///cvzueiha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 265,241: 16x26
        ///#2 @ 584,382: 12x8
        ///#3 @ 584,823: 22x10
        ///#4 @ 336,138: 26x22
        ///#5 @ 527,903: 26x18
        ///#6 @ 596,224: 23x20
        ///#7 @ 770,344: 15x12
        ///#8 @ 191,889: 17x11
        ///#9 @ 493,316: 12x19
        ///#10 @ 648,614: 26x28
        ///#11 @ 217,27: 25x20
        ///#12 @ 819,550: 16x12
        ///#13 @ 314,74: 18x25
        ///#14 @ 844,633: 22x16
        ///#15 @ 793,382: 11x18
        ///#16 @ 899,263: 16x14
        ///#17 @ 713,844: 11x21
        ///#18 @ 502,903: 19x12
        ///#19 @ 434,163: 29x24
        ///#20 @ 307,339: 23x15
        ///#21 @ 683,931: 10x22
        ///#22 @ 950,568: 23x15
        ///#23 @ 514,250: 11x19
        ///#24 @ 383,822: 28x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3Input {
            get {
                return ResourceManager.GetString("Day3Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-02-28 00:47] falls asleep
        ///[1518-10-23 23:47] Guard #1627 begins shift
        ///[1518-10-25 00:41] wakes up
        ///[1518-09-13 00:04] Guard #571 begins shift
        ///[1518-05-10 00:10] wakes up
        ///[1518-03-07 00:02] Guard #1901 begins shift
        ///[1518-10-10 00:59] wakes up
        ///[1518-08-21 00:25] falls asleep
        ///[1518-06-18 00:25] falls asleep
        ///[1518-11-19 00:24] falls asleep
        ///[1518-04-13 00:42] wakes up
        ///[1518-11-01 23:51] Guard #1697 begins shift
        ///[1518-05-14 00:14] falls asleep
        ///[1518-08-04 00:49] wakes up
        ///[1518-08-07 00:47] fall [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QqGgPfHhOiIoFMmUXxOooBbOqXxcCbBQboOBusSTTtjJATtafFkKZzxEeeEXZzuUcCtwWHhpuyYtTZzTyYtUBzOoyYfiIFaAaSsAZyGgOtTPpVmknNKuUMnNgGvSFfTtYyMmcoOEeCsSgGsowWMHhWSsxXWiTtjJIwaAwbHhwWBhHVvUupPlmMyYLYymuUbDdBWwJjErRhHKiUmMuTtaAwAaEeFfWIwWYyoOkkvVbXsSxdqQDBKIieCcCcvVYsSbjdDzZnNOoJRrpPhrRzCcFfZmMzZeEiIHyzZYhWzZYyiIwXxgTtPjvVJAapDSsdsYySBbJjcCfFGDzZaBbAFNncCPbbBAaBjVvJuZzvVAaGJjgRrqAaXxQUdDsSUlLnNuMmgGQqExqQXtTeIiHeEsSwWhpfuNpPnUTkKKktSsdjJaAJjMTtmHbBrRfFZzPRrhzSsZMmBbdDCFzZRrfTtciIjJHaUuaAjqQLlmuBbUhHVvbiVvZzNnIBMzZJwWQqTt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 249, 60
        ///150, 332
        ///174, 83
        ///287, 329
        ///102, 338
        ///111, 201
        ///259, 96
        ///277, 161
        ///143, 288
        ///202, 311
        ///335, 55
        ///239, 148
        ///137, 224
        ///48, 214
        ///186, 87
        ///282, 334
        ///147, 157
        ///246, 191
        ///241, 181
        ///286, 129
        ///270, 287
        ///79, 119
        ///189, 263
        ///324, 280
        ///316, 279
        ///221, 236
        ///327, 174
        ///141, 82
        ///238, 317
        ///64, 264
        ///226, 151
        ///110, 110
        ///336, 194
        ///235, 333
        ///237, 55
        ///230, 137
        ///267, 44
        ///258, 134
        ///223, 42
        ///202, 76
        ///159, 135
        ///229, 238
        ///197, 83
        ///173, 286
        ///123, 90
        ///314, 165
        ///140, 338
        ///347, 60
        ///108, 76
        ///268, 329.
        /// </summary>
        internal static string Day6Input {
            get {
                return ResourceManager.GetString("Day6Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Q must be finished before step O can begin.
        ///Step Z must be finished before step G can begin.
        ///Step W must be finished before step V can begin.
        ///Step C must be finished before step X can begin.
        ///Step O must be finished before step E can begin.
        ///Step K must be finished before step N can begin.
        ///Step P must be finished before step I can begin.
        ///Step X must be finished before step D can begin.
        ///Step N must be finished before step E can begin.
        ///Step F must be finished before step A can begin.
        ///Step U must  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7Input {
            get {
                return ResourceManager.GetString("Day7Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 11 6 2 4 3 3 6 1 5 0 7 1 8 5 2 4 1 1 1 1 3 2 1 1 9 0 7 6 6 1 4 1 2 2 1 1 3 3 2 2 1 1 1 1 6 0 10 4 7 5 5 3 3 8 4 4 1 1 3 1 2 1 1 4 5 3 2 3 5 3 4 1 9 0 9 8 7 1 2 3 1 9 1 3 1 3 1 2 3 2 1 3 2 1 9 0 10 5 2 7 8 7 9 6 3 8 1 1 3 3 3 3 1 2 1 2 1 5 0 8 4 4 8 2 2 7 4 1 2 1 2 3 1 3 3 2 3 3 7 1 9 0 10 9 3 1 4 8 9 2 6 7 4 1 3 1 1 3 3 3 1 3 1 7 0 6 8 7 6 3 4 1 1 1 1 1 1 2 1 1 7 0 8 1 9 5 2 2 1 1 5 3 3 1 3 3 2 2 5 2 4 1 5 4 2 3 5 1 6 0 6 1 5 2 1 8 5 1 3 1 1 1 3 1 8 0 10 4 3 1 7 1 8 6 9 9 9 1 1 1 1 2 3 1 2 1 7 0 11 2 3 1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8Input {
            get {
                return ResourceManager.GetString("Day8Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 424 players; last marble is worth 71482 points.
        /// </summary>
        internal static string Day9Input {
            get {
                return ResourceManager.GetString("Day9Input", resourceCulture);
            }
        }
    }
}
