//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventCodeSolution {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventCodeSolution.InputResources", typeof(InputResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position=&lt; 21373,  53216&gt; velocity=&lt;-2, -5&gt;
        ///position=&lt;-10460, -31621&gt; velocity=&lt; 1,  3&gt;
        ///position=&lt; 21353, -42222&gt; velocity=&lt;-2,  4&gt;
        ///position=&lt; 53136, -52828&gt; velocity=&lt;-5,  5&gt;
        ///position=&lt; 42542, -21012&gt; velocity=&lt;-4,  2&gt;
        ///position=&lt;-42304, -10407&gt; velocity=&lt; 4,  1&gt;
        ///position=&lt; 21337,  21407&gt; velocity=&lt;-2, -2&gt;
        ///position=&lt;-42297,  42612&gt; velocity=&lt; 4, -4&gt;
        ///position=&lt; 31921, -42227&gt; velocity=&lt;-3,  4&gt;
        ///position=&lt;-21087,  10800&gt; velocity=&lt; 2, -1&gt;
        ///position=&lt;-52877, -31621&gt; velocity=&lt; 5,  3&gt;
        ///position=&lt; 42532, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1308.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initial state: ..#..###...#####.#.#...####.#..####..###.##.#.#.##.#....#....#.####...#....###.###..##.#....#######
        ///
        ///..### =&gt; .
        ///.##.# =&gt; #
        ///#..#. =&gt; .
        ///#.#.# =&gt; #
        ///###.. =&gt; #
        ///.#..# =&gt; .
        ///##..# =&gt; #
        ///.###. =&gt; #
        ///..#.. =&gt; .
        ///..... =&gt; .
        ///##### =&gt; .
        ///.#... =&gt; #
        ///...#. =&gt; #
        ///#...# =&gt; #
        ///####. =&gt; .
        ///.#### =&gt; .
        ///##.## =&gt; #
        ///...## =&gt; .
        ///..##. =&gt; .
        ///#.##. =&gt; .
        ///#.... =&gt; .
        ///.#.#. =&gt; .
        ///..#.# =&gt; #
        ///#.#.. =&gt; #
        ///##... =&gt; #
        ///##.#. =&gt; .
        ///#..## =&gt; .
        ///.##.. =&gt; .
        ///#.### =&gt; .
        ///....# =&gt; .
        ///.#.## =&gt; #
        ///###.# =&gt; #.
        /// </summary>
        internal static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                          /----&gt;--------------------------------------------------\                                                    
        ///                                         |/------------------------&gt;---------------------\       |                                                    
        ///                                         ||                                              |       |              /-----------------------\/---------\  
        ///                                         ||              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13Input {
            get {
                return ResourceManager.GetString("Day13Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 990941.
        /// </summary>
        internal static string Day14Input {
            get {
                return ResourceManager.GetString("Day14Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################################
        ///##########..........############
        ///########G..................#####
        ///#######..G.GG...............####
        ///#######....G.......#......######
        ///########.G.G...............#E..#
        ///#######G.................#.....#
        ///########.......................#
        ///########G.....G....#.....##....#
        ///########.....#....G.........####
        ///#########..........##....E.E#.##
        ///##########G..G..........#####.##
        ///##########....#####G....####E.##
        ///######....G..#######.....#.....#
        ///###....#....#########......#####
        ///## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15Input {
            get {
                return ResourceManager.GetString("Day15Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before: [0, 2, 2, 2]
        ///11 3 3 3
        ///After:  [0, 2, 2, 0]
        ///
        ///Before: [3, 2, 1, 1]
        ///11 2 3 3
        ///After:  [3, 2, 1, 0]
        ///
        ///Before: [1, 2, 2, 1]
        ///5 3 2 2
        ///After:  [1, 2, 1, 1]
        ///
        ///Before: [1, 0, 2, 2]
        ///14 0 2 2
        ///After:  [1, 0, 0, 2]
        ///
        ///Before: [3, 2, 3, 3]
        ///10 1 3 3
        ///After:  [3, 2, 3, 0]
        ///
        ///Before: [1, 1, 2, 1]
        ///14 0 2 3
        ///After:  [1, 1, 2, 0]
        ///
        ///Before: [2, 1, 2, 0]
        ///6 2 2 0
        ///After:  [1, 1, 2, 0]
        ///
        ///Before: [1, 1, 3, 1]
        ///13 1 2 0
        ///After:  [0, 1, 3, 1]
        ///
        ///Before: [1, 1, 1, 3]
        ///10 2 3 1
        ///After:  [1, 0, 1, 3]
        ///
        ///Before: [3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16Input {
            get {
                return ResourceManager.GetString("Day16Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x=732, y=143..151
        ///y=438, x=555..569
        ///x=731, y=1620..1626
        ///x=591, y=101..107
        ///x=536, y=346..359
        ///x=524, y=244..254
        ///x=659, y=418..428
        ///x=523, y=27..38
        ///x=631, y=1144..1146
        ///x=683, y=1286..1289
        ///y=729, x=536..546
        ///x=624, y=1197..1206
        ///y=703, x=639..667
        ///x=625, y=623..625
        ///x=488, y=369..386
        ///x=570, y=214..217
        ///y=737, x=711..730
        ///x=484, y=1354..1378
        ///x=527, y=491..502
        ///y=914, x=617..623
        ///y=1104, x=680..685
        ///x=597, y=1181..1186
        ///x=625, y=1644..1653
        ///x=509, y=1452..1455
        ///y=113, x=603..611
        ///x=734, y=1523..1537
        ///x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day17Input {
            get {
                return ResourceManager.GetString("Day17Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.|.##|....|#|.#...#.|#.#.....|..#..#|.#..|##.##.|
        ///.|....|.#|.#..|#|..#.|.....#....##.||..#......||.#
        ///|.|...|#..|....#..#.......#......#..#|#|..||.|....
        ///..|||#..#.#||.#..#......||.|#...#.#.|..||.#..|.#||
        ///#.##....##.#|........||..#||#.##.#.|||...|#..|||.#
        ///..#||.#......#||..|.#.##..|##..|#...#|...#......|.
        ///|##.#|#...|||####.##....|.....#....#######.......#
        ///.##..#.......|.#.#|##...|..##......#..|.#..#.#|..#
        ///###..###|#..|.#.#..|.#........|.#||.......#.||||..
        ///|.....|.....|##..|..||.......#|#.#.##.#.##.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day18Input {
            get {
                return ResourceManager.GetString("Day18Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ip 2
        ///addi 2 16 2
        ///seti 1 0 4
        ///seti 1 0 1
        ///mulr 4 1 3
        ///eqrr 3 5 3
        ///addr 3 2 2
        ///addi 2 1 2
        ///addr 4 0 0
        ///addi 1 1 1
        ///gtrr 1 5 3
        ///addr 2 3 2
        ///seti 2 5 2
        ///addi 4 1 4
        ///gtrr 4 5 3
        ///addr 3 2 2
        ///seti 1 9 2
        ///mulr 2 2 2
        ///addi 5 2 5
        ///mulr 5 5 5
        ///mulr 2 5 5
        ///muli 5 11 5
        ///addi 3 8 3
        ///mulr 3 2 3
        ///addi 3 5 3
        ///addr 5 3 5
        ///addr 2 0 2
        ///seti 0 9 2
        ///setr 2 8 3
        ///mulr 3 2 3
        ///addr 2 3 3
        ///mulr 2 3 3
        ///muli 3 14 3
        ///mulr 3 2 3
        ///addr 5 3 5
        ///seti 0 6 0
        ///seti 0 0 2.
        /// </summary>
        internal static string Day19Input {
            get {
                return ResourceManager.GetString("Day19Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +16
        ///-2
        ///-5
        ///+1
        ///-12
        ///-1
        ///-8
        ///+12
        ///+5
        ///-18
        ///-12
        ///-11
        ///-1
        ///+2
        ///-8
        ///-6
        ///-1
        ///-17
        ///-18
        ///+16
        ///-4
        ///+18
        ///+7
        ///-4
        ///+13
        ///+11
        ///-5
        ///+11
        ///-8
        ///+15
        ///+8
        ///-16
        ///+15
        ///+10
        ///-19
        ///-17
        ///+5
        ///-13
        ///+10
        ///+14
        ///+16
        ///+8
        ///+14
        ///-8
        ///+19
        ///-17
        ///+14
        ///+12
        ///+8
        ///+9
        ///-11
        ///+1
        ///+2
        ///-16
        ///+19
        ///+13
        ///-5
        ///+6
        ///-10
        ///-6
        ///+4
        ///-15
        ///+20
        ///+18
        ///-14
        ///+15
        ///+3
        ///+4
        ///-3
        ///-9
        ///+1
        ///+18
        ///+8
        ///+2
        ///-11
        ///+19
        ///-3
        ///-10
        ///+14
        ///+12
        ///+6
        ///-17
        ///-14
        ///-10
        ///-18
        ///+19
        ///+4
        ///+12
        ///-18
        ///-4
        ///-8
        ///-4
        ///-20
        ///-16
        ///-1
        ///-18
        ///+2
        ///-17
        ///-17
        ///+7
        ///-12
        ///-3
        ///+4
        ///+9
        ///+6
        ///+9
        ///+6
        ///+1
        ///-17
        ///+13
        ///+14
        ///-2
        ///+8
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^WSWSWSWNWSSWWWWWNENESENNWWNENENESENEEES(SWNWSS(WW(SS|N(W|E))|E)|EEENNEENESSWSSSSEENNESSENESSWWWWSWWWSWWSSSEEENEENWW(WWSEWNEE|)NEEESSENEENN(WSWNWESENE|)ESENENEEENEESWSESWWNWWSESWW(N|WSEESSSWWWNN(ESENSWNW|)N(WSW(SESSWSSSESSSSWWWSWWNNNENESS(WSNE|)EENWN(E|NWNENWNEN(NWWS(WN(NEEEWWWS|)WWWSEESSESWWNNWWSWNWSWNWNWWSSWWWSESENESENN(ESSSSSSENNNESENNN(WWSEWNEE|)ESE(ESWSW(N|SESSWWW(NE(NWES|)E|SESWWWWWSESWWWWWNWWSWWWSSSWWNWSWWNENWNENENNESSE(EEENWNNWSSWNNNNWWSWNWNENNWNNENEESENESEENNW(WWWWNWSWSWSSSWNNWSSWWNENWWNNNNWNWSWSSS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day20Input {
            get {
                return ResourceManager.GetString("Day20Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ip 4
        ///seti 123 0 2
        ///bani 2 456 2
        ///eqri 2 72 2
        ///addr 2 4 4
        ///seti 0 0 4
        ///seti 0 1 2
        ///bori 2 65536 5
        ///seti 16123384 4 2
        ///bani 5 255 3
        ///addr 2 3 2
        ///bani 2 16777215 2
        ///muli 2 65899 2
        ///bani 2 16777215 2
        ///gtir 256 5 3
        ///addr 3 4 4
        ///addi 4 1 4
        ///seti 27 6 4
        ///seti 0 3 3
        ///addi 3 1 1
        ///muli 1 256 1
        ///gtrr 1 5 1
        ///addr 1 4 4
        ///addi 4 1 4
        ///seti 25 6 4
        ///addi 3 1 3
        ///seti 17 3 4
        ///setr 3 8 5
        ///seti 7 2 4
        ///eqrr 2 0 3
        ///addr 3 4 4
        ///seti 5 3 4.
        /// </summary>
        internal static string Day21Input {
            get {
                return ResourceManager.GetString("Day21Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depth: 9171
        ///target: 7,721.
        /// </summary>
        internal static string Day22Input {
            get {
                return ResourceManager.GetString("Day22Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pos=&lt;10,12,12&gt;, r=2
        ///pos=&lt;12,14,12&gt;, r=2
        ///pos=&lt;16,12,12&gt;, r=4
        ///pos=&lt;14,14,14&gt;, r=6
        ///pos=&lt;50,50,50&gt;, r=200
        ///pos=&lt;10,10,10&gt;, r=5.
        /// </summary>
        internal static string Day23Input {
            get {
                return ResourceManager.GetString("Day23Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immune System:
        ///522 units each with 9327 hit points with an attack that does 177 slashing damage at initiative 14
        ///2801 units each with 3302 hit points with an attack that does 10 bludgeoning damage at initiative 7
        ///112 units each with 11322 hit points with an attack that does 809 slashing damage at initiative 8
        ///2974 units each with 9012 hit points with an attack that does 23 slashing damage at initiative 11
        ///4805 units each with 8717 hit points (weak to radiation) with an attack that does 15 bludgeoning d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day24Input {
            get {
                return ResourceManager.GetString("Day24Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1,-7,-2,-6
        ///6,-6,6,0
        ///0,8,-5,-3
        ///-1,-5,3,2
        ///4,3,0,-7
        ///0,5,0,3
        ///-1,4,0,-5
        ///5,-7,5,-4
        ///6,4,1,1
        ///4,-3,-1,4
        ///4,2,3,-3
        ///4,5,8,6
        ///-7,8,-4,-1
        ///3,-3,0,-5
        ///-1,4,8,2
        ///-7,6,-7,-3
        ///-3,-6,1,-8
        ///7,0,0,-2
        ///-3,2,-3,2
        ///8,-8,-8,-2
        ///-5,8,-3,1
        ///-6,-7,5,5
        ///1,-3,7,-3
        ///-4,7,0,0
        ///7,-3,3,-4
        ///2,3,-6,6
        ///0,-6,6,4
        ///-4,-2,8,-5
        ///0,4,-4,6
        ///8,-7,-5,2
        ///-5,-5,-8,6
        ///0,2,7,-7
        ///8,1,-7,0
        ///-5,0,5,4
        ///-7,-8,-6,4
        ///7,-7,3,-4
        ///0,-2,-2,-7
        ///-1,0,1,-5
        ///-6,-6,0,2
        ///-4,6,8,6
        ///1,8,2,5
        ///5,-1,1,3
        ///6,6,-1,-1
        ///-1,6,-5,4
        ///8,-3,-4,3
        ///8,-3,-6,5
        ///-3,6,-8,-3
        ///-7,0,5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day25Input {
            get {
                return ResourceManager.GetString("Day25Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cvfueihajytpmrdkgsxfqplbxn
        ///cbzueihajytnmrdkgtxfqplbwn
        ///cvzucihajytomrdkgstfqplqwn
        ///cvzueilajytomrdkgsxfqwnbwn
        ///cvzueihajytomrdkgsgwqphbwn
        ///wuzuerhajytomrdkgsxfqplbwn
        ///cyzueifajybomrdkgsxfqplbwn
        ///cvzueihajxtomrdkgpxfqplmwn
        ///ivzfevhajytomrdkgsxfqplbwn
        ///cvzueihajytomrdlgsxfqphbbn
        ///uvzueihajjtomrdkgsxfqpobwn
        ///cvzupihajytomrdkgsxfqplpwe
        ///cvzueihajyvomrdkgsxfqplbrl
        ///cczueihajytomrdkgsnfqpxbwn
        ///cvzueigajytdmrdkgsxyqplbwn
        ///cvzujihljytomrdkgsxuqplbwn
        ///cvzueisajytomrddgsxkqplbwn
        ///cvzneihajytomrdkgsgaqplbwn
        ///cvzueiha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 265,241: 16x26
        ///#2 @ 584,382: 12x8
        ///#3 @ 584,823: 22x10
        ///#4 @ 336,138: 26x22
        ///#5 @ 527,903: 26x18
        ///#6 @ 596,224: 23x20
        ///#7 @ 770,344: 15x12
        ///#8 @ 191,889: 17x11
        ///#9 @ 493,316: 12x19
        ///#10 @ 648,614: 26x28
        ///#11 @ 217,27: 25x20
        ///#12 @ 819,550: 16x12
        ///#13 @ 314,74: 18x25
        ///#14 @ 844,633: 22x16
        ///#15 @ 793,382: 11x18
        ///#16 @ 899,263: 16x14
        ///#17 @ 713,844: 11x21
        ///#18 @ 502,903: 19x12
        ///#19 @ 434,163: 29x24
        ///#20 @ 307,339: 23x15
        ///#21 @ 683,931: 10x22
        ///#22 @ 950,568: 23x15
        ///#23 @ 514,250: 11x19
        ///#24 @ 383,822: 28x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3Input {
            get {
                return ResourceManager.GetString("Day3Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-02-28 00:47] falls asleep
        ///[1518-10-23 23:47] Guard #1627 begins shift
        ///[1518-10-25 00:41] wakes up
        ///[1518-09-13 00:04] Guard #571 begins shift
        ///[1518-05-10 00:10] wakes up
        ///[1518-03-07 00:02] Guard #1901 begins shift
        ///[1518-10-10 00:59] wakes up
        ///[1518-08-21 00:25] falls asleep
        ///[1518-06-18 00:25] falls asleep
        ///[1518-11-19 00:24] falls asleep
        ///[1518-04-13 00:42] wakes up
        ///[1518-11-01 23:51] Guard #1697 begins shift
        ///[1518-05-14 00:14] falls asleep
        ///[1518-08-04 00:49] wakes up
        ///[1518-08-07 00:47] fall [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QqGgPfHhOiIoFMmUXxOooBbOqXxcCbBQboOBusSTTtjJATtafFkKZzxEeeEXZzuUcCtwWHhpuyYtTZzTyYtUBzOoyYfiIFaAaSsAZyGgOtTPpVmknNKuUMnNgGvSFfTtYyMmcoOEeCsSgGsowWMHhWSsxXWiTtjJIwaAwbHhwWBhHVvUupPlmMyYLYymuUbDdBWwJjErRhHKiUmMuTtaAwAaEeFfWIwWYyoOkkvVbXsSxdqQDBKIieCcCcvVYsSbjdDzZnNOoJRrpPhrRzCcFfZmMzZeEiIHyzZYhWzZYyiIwXxgTtPjvVJAapDSsdsYySBbJjcCfFGDzZaBbAFNncCPbbBAaBjVvJuZzvVAaGJjgRrqAaXxQUdDsSUlLnNuMmgGQqExqQXtTeIiHeEsSwWhpfuNpPnUTkKKktSsdjJaAJjMTtmHbBrRfFZzPRrhzSsZMmBbdDCFzZRrfTtciIjJHaUuaAjqQLlmuBbUhHVvbiVvZzNnIBMzZJwWQqTt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 249, 60
        ///150, 332
        ///174, 83
        ///287, 329
        ///102, 338
        ///111, 201
        ///259, 96
        ///277, 161
        ///143, 288
        ///202, 311
        ///335, 55
        ///239, 148
        ///137, 224
        ///48, 214
        ///186, 87
        ///282, 334
        ///147, 157
        ///246, 191
        ///241, 181
        ///286, 129
        ///270, 287
        ///79, 119
        ///189, 263
        ///324, 280
        ///316, 279
        ///221, 236
        ///327, 174
        ///141, 82
        ///238, 317
        ///64, 264
        ///226, 151
        ///110, 110
        ///336, 194
        ///235, 333
        ///237, 55
        ///230, 137
        ///267, 44
        ///258, 134
        ///223, 42
        ///202, 76
        ///159, 135
        ///229, 238
        ///197, 83
        ///173, 286
        ///123, 90
        ///314, 165
        ///140, 338
        ///347, 60
        ///108, 76
        ///268, 329.
        /// </summary>
        internal static string Day6Input {
            get {
                return ResourceManager.GetString("Day6Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Q must be finished before step O can begin.
        ///Step Z must be finished before step G can begin.
        ///Step W must be finished before step V can begin.
        ///Step C must be finished before step X can begin.
        ///Step O must be finished before step E can begin.
        ///Step K must be finished before step N can begin.
        ///Step P must be finished before step I can begin.
        ///Step X must be finished before step D can begin.
        ///Step N must be finished before step E can begin.
        ///Step F must be finished before step A can begin.
        ///Step U must  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7Input {
            get {
                return ResourceManager.GetString("Day7Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 11 6 2 4 3 3 6 1 5 0 7 1 8 5 2 4 1 1 1 1 3 2 1 1 9 0 7 6 6 1 4 1 2 2 1 1 3 3 2 2 1 1 1 1 6 0 10 4 7 5 5 3 3 8 4 4 1 1 3 1 2 1 1 4 5 3 2 3 5 3 4 1 9 0 9 8 7 1 2 3 1 9 1 3 1 3 1 2 3 2 1 3 2 1 9 0 10 5 2 7 8 7 9 6 3 8 1 1 3 3 3 3 1 2 1 2 1 5 0 8 4 4 8 2 2 7 4 1 2 1 2 3 1 3 3 2 3 3 7 1 9 0 10 9 3 1 4 8 9 2 6 7 4 1 3 1 1 3 3 3 1 3 1 7 0 6 8 7 6 3 4 1 1 1 1 1 1 2 1 1 7 0 8 1 9 5 2 2 1 1 5 3 3 1 3 3 2 2 5 2 4 1 5 4 2 3 5 1 6 0 6 1 5 2 1 8 5 1 3 1 1 1 3 1 8 0 10 4 3 1 7 1 8 6 9 9 9 1 1 1 1 2 3 1 2 1 7 0 11 2 3 1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8Input {
            get {
                return ResourceManager.GetString("Day8Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 424 players; last marble is worth 71482 points.
        /// </summary>
        internal static string Day9Input {
            get {
                return ResourceManager.GetString("Day9Input", resourceCulture);
            }
        }
    }
}
